[Interface]
Address = 192.168.6.210/32
DNS = 1.1.1.1,8.8.8.8
PrivateKey = wGvHe4R7zOKduwNyc12wZTqEvRLwKM74VooSVhe7Klg=

[Peer]
PublicKey=U/zKW8ujkTZJVqcvUlvtGYYxpbA+3q3hxNBcXf3G9V0=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = in6.vpnjantit.com:1024
